let uniOrder = [
    "All",
    "Struthioniformes",
    "Rheiformes",
    "Tinamiformes",
    "Casuariiformes",
    "Apterygiformes",
    "Anseriformes",
    "Galliformes",
    "Phoenicopteriformes",
    "Podicipediformes",
    "Columbiformes",
    "Mesitornithiformes",
    "Pterocliformes",
    "Otidiformes",
    "Musophagiformes",
    "Cuculiformes",
    "Caprimulgiformes",
    "Opisthocomiformes",
    "Gruiformes",
    "Charadriiformes",
    "Eurypygiformes",
    "Phaethontiformes",
    "Gaviiformes",
    "Sphenisciformes",
    "Procellariiformes",
    "Ciconiiformes",
    "Suliformes",
    "Pelecaniformes",
    "Cathartiformes",
    "Accipitriformes",
    "Strigiformes",
    "Coliiformes",
    "Leptosomiformes",
    "Trogoniformes",
    "Bucerotiformes",
    "Coraciiformes",
    "Galbuliformes",
    "Piciformes",
    "Cariamiformes",
    "Falconiformes",
    "Psittaciformes",
    "Passeriformes",
    ""
];
let uniFamily = [
    "All",
    "Struthionidae (Ostriches)",
    "Rheidae (Rheas)",
    "Tinamidae (Tinamous)",
    "Casuariidae (Cassowaries and Emu)",
    "Apterygidae (Kiwis)",
    "Anhimidae (Screamers)",
    "Anseranatidae (Magpie Goose)",
    "Anatidae (Ducks, Geese, and Waterfowl)",
    "Megapodiidae (Megapodes)",
    "Cracidae (Guans, Chachalacas, and Curassows)",
    "Numididae (Guineafowl)",
    "Odontophoridae (New World Quail)",
    "Phasianidae (Pheasants, Grouse, and Allies)",
    "Phoenicopteridae (Flamingos)",
    "Podicipedidae (Grebes)",
    "Columbidae (Pigeons and Doves)",
    "Mesitornithidae (Mesites)",
    "Pteroclidae (Sandgrouse)",
    "Otididae (Bustards)",
    "Musophagidae (Turacos)",
    "Cuculidae (Cuckoos)",
    "Podargidae (Frogmouths)",
    "Caprimulgidae (Nightjars and Allies)",
    "Nyctibiidae (Potoos)",
    "Steatornithidae (Oilbird)",
    "Aegothelidae (Owlet-nightjars)",
    "Apodidae (Swifts)",
    "Hemiprocnidae (Treeswifts)",
    "Trochilidae (Hummingbirds)",
    "Opisthocomidae (Hoatzin)",
    "Sarothruridae (Flufftails)",
    "Rallidae (Rails, Gallinules, and Coots)",
    "Heliornithidae (Finfoots)",
    "Aramidae (Limpkin)",
    "Psophiidae (Trumpeters)",
    "Gruidae (Cranes)",
    "Chionidae (Sheathbills)",
    "Pluvianellidae (Magellanic Plover)",
    "Burhinidae (Thick-knees)",
    "Pluvianidae (Egyptian Plover)",
    "Recurvirostridae (Stilts and Avocets)",
    "Ibidorhynchidae (Ibisbill)",
    "Haematopodidae (Oystercatchers)",
    "Charadriidae (Plovers and Lapwings)",
    "Pedionomidae (Plains-wanderer)",
    "Thinocoridae (Seedsnipes)",
    "Rostratulidae (Painted-Snipes)",
    "Jacanidae (Jacanas)",
    "Scolopacidae (Sandpipers and Allies)",
    "Turnicidae (Buttonquail)",
    "Dromadidae (Crab-Plover)",
    "Glareolidae (Pratincoles and Coursers)",
    "Stercorariidae (Skuas and Jaegers)",
    "Alcidae (Auks, Murres, and Puffins)",
    "Laridae (Gulls, Terns, and Skimmers)",
    "Rhynochetidae (Kagu)",
    "Eurypygidae (Sunbittern)",
    "Phaethontidae (Tropicbirds)",
    "Gaviidae (Loons)",
    "Spheniscidae (Penguins)",
    "Diomedeidae (Albatrosses)",
    "Oceanitidae (Southern Storm-Petrels)",
    "Hydrobatidae (Northern Storm-Petrels)",
    "Procellariidae (Shearwaters and Petrels)",
    "Ciconiidae (Storks)",
    "Fregatidae (Frigatebirds)",
    "Sulidae (Boobies and Gannets)",
    "Anhingidae (Anhingas)",
    "Phalacrocoracidae (Cormorants and Shags)",
    "Pelecanidae (Pelicans)",
    "Balaenicipitidae (Shoebill)",
    "Scopidae (Hamerkop)",
    "Ardeidae (Herons, Egrets, and Bitterns)",
    "Threskiornithidae (Ibises and Spoonbills)",
    "Cathartidae (New World Vultures)",
    "Sagittariidae (Secretarybird)",
    "Pandionidae (Osprey)",
    "Accipitridae (Hawks, Eagles, and Kites)",
    "Tytonidae (Barn-Owls)",
    "Strigidae (Owls)",
    "Coliidae (Mousebirds)",
    "Leptosomidae (Cuckoo-roller)",
    "Trogonidae (Trogons)",
    "Upupidae (Hoopoes)",
    "Phoeniculidae (Woodhoopoes and Scimitarbills)",
    "Bucorvidae (Ground-Hornbills)",
    "Bucerotidae (Hornbills)",
    "Todidae (Todies)",
    "Momotidae (Motmots)",
    "Alcedinidae (Kingfishers)",
    "Meropidae (Bee-eaters)",
    "Coraciidae (Rollers)",
    "Brachypteraciidae (Ground-Rollers)",
    "Bucconidae (Puffbirds)",
    "Galbulidae (Jacamars)",
    "Lybiidae (African Barbets)",
    "Megalaimidae (Asian Barbets)",
    "Capitonidae (New World Barbets)",
    "Semnornithidae (Toucan-Barbets)",
    "Ramphastidae (Toucans)",
    "Indicatoridae (Honeyguides)",
    "Picidae (Woodpeckers)",
    "Cariamidae (Seriemas)",
    "Falconidae (Falcons and Caracaras)",
    "Strigopidae (New Zealand Parrots)",
    "Cacatuidae (Cockatoos)",
    "Psittaculidae (Old World Parrots)",
    "Psittacidae (New World and African Parrots)",
    "Acanthisittidae (New Zealand Wrens)",
    "Calyptomenidae (African and Green Broadbills)",
    "Eurylaimidae (Asian and Grauer's Broadbills)",
    "Sapayoidae (Sapayoa)",
    "Philepittidae (Asities)",
    "Pittidae (Pittas)",
    "Thamnophilidae (Typical Antbirds)",
    "Melanopareiidae (Crescentchests)",
    "Conopophagidae (Gnateaters)",
    "Grallariidae (Antpittas)",
    "Rhinocryptidae (Tapaculos)",
    "Formicariidae (Antthrushes)",
    "Furnariidae (Ovenbirds and Woodcreepers)",
    "Pipridae (Manakins)",
    "Cotingidae (Cotingas)",
    "Tityridae (Tityras and Allies)",
    "Oxyruncidae (Sharpbill, Royal Flycatcher, and Allies)",
    "Tyrannidae (Tyrant Flycatchers)",
    "Menuridae (Lyrebirds)",
    "Atrichornithidae (Scrub-birds)",
    "Ptilonorhynchidae (Bowerbirds)",
    "Climacteridae (Australasian Treecreepers)",
    "Maluridae (Fairywrens)",
    "Meliphagidae (Honeyeaters)",
    "Dasyornithidae (Bristlebirds)",
    "Pardalotidae (Pardalotes)",
    "Acanthizidae (Thornbills and Allies)",
    "Pomatostomidae (Pseudo-Babblers)",
    "Orthonychidae (Logrunners)",
    "Cinclosomatidae (Quail-thrushes and Jewel-babblers)",
    "Campephagidae (Cuckooshrikes)",
    "Mohouidae (Whiteheads)",
    "Neosittidae (Sittellas)",
    "Psophodidae (Whipbirds and Wedgebills)",
    "Eulacestomatidae (Ploughbill)",
    "Oreoicidae (Australo-Papuan Bellbirds)",
    "Falcunculidae (Shrike-tits)",
    "Paramythiidae (Tit Berrypecker and Crested Berrypecker)",
    "Vireonidae (Vireos, Shrike-Babblers, and Erpornis)",
    "Pachycephalidae (Whistlers and Allies)",
    "Oriolidae (Old World Orioles)",
    "Machaerirhynchidae (Boatbills)",
    "Artamidae (Woodswallows, Bellmagpies, and Allies)",
    "Rhagologidae (Mottled Berryhunter)",
    "Platysteiridae (Wattle-eyes and Batises)",
    "Vangidae (Vangas, Helmetshrikes, and Allies)",
    "Pityriasidae (Bristlehead)",
    "Aegithinidae (Ioras)",
    "Malaconotidae (Bushshrikes and Allies)",
    "Rhipiduridae (Fantails)",
    "Dicruridae (Drongos)",
    "Paradisaeidae (Birds-of-Paradise)",
    "Ifritidae (Ifrita)",
    "Monarchidae (Monarch Flycatchers)",
    "Corcoracidae (White-winged Chough and Apostlebird)",
    "Melampittidae (Melampittas)",
    "Platylophidae (Crested Shrikejay)",
    "Laniidae (Shrikes)",
    "Corvidae (Crows, Jays, and Magpies)",
    "Cnemophilidae (Satinbirds)",
    "Melanocharitidae (Berrypeckers and Longbills)",
    "Callaeidae (Wattlebirds)",
    "Notiomystidae (Stitchbird)",
    "Petroicidae (Australasian Robins)",
    "Picathartidae (Rockfowl)",
    "Chaetopidae (Rockjumpers)",
    "Eupetidae (Rail-babbler)",
    "Hyliotidae (Hyliotas)",
    "Stenostiridae (Fairy Flycatchers)",
    "Paridae (Tits, Chickadees, and Titmice)",
    "Remizidae (Penduline-Tits)",
    "Alaudidae (Larks)",
    "Panuridae (Bearded Reedling)",
    "Nicatoridae (Nicators)",
    "Macrosphenidae (African Warblers)",
    "Cisticolidae (Cisticolas and Allies)",
    "Acrocephalidae (Reed Warblers and Allies)",
    "Locustellidae (Grassbirds and Allies)",
    "Donacobiidae (Donacobius)",
    "Bernieridae (Malagasy Warblers)",
    "Pnoepygidae (Cupwings)",
    "Hirundinidae (Swallows)",
    "Pycnonotidae (Bulbuls)",
    "Phylloscopidae (Leaf Warblers)",
    "Scotocercidae (Bush Warblers and Allies)",
    "Aegithalidae (Long-tailed Tits)",
    "Sylviidae (Sylviid Warblers, Parrotbills, and Allies)",
    "Zosteropidae (White-eyes, Yuhinas, and Allies)",
    "Timaliidae (Tree-Babblers, Scimitar-Babblers, and Allies)",
    "Pellorneidae (Ground Babblers and Allies)",
    "Leiothrichidae (Laughingthrushes and Allies)",
    "Regulidae (Kinglets)",
    "Tichodromidae (Wallcreeper)",
    "Sittidae (Nuthatches)",
    "Certhiidae (Treecreepers)",
    "Polioptilidae (Gnatcatchers)",
    "Troglodytidae (Wrens)",
    "Elachuridae (Spotted Elachura)",
    "Cinclidae (Dippers)",
    "Buphagidae (Oxpeckers)",
    "Sturnidae (Starlings)",
    "Mimidae (Mockingbirds and Thrashers)",
    "Turdidae (Thrushes and Allies)",
    "Muscicapidae (Old World Flycatchers)",
    "Bombycillidae (Waxwings)",
    "Mohoidae (Hawaiian Honeyeaters)",
    "Ptiliogonatidae (Silky-flycatchers)",
    "Dulidae (Palmchat)",
    "Hylocitreidae (Hylocitrea)",
    "Hypocoliidae (Hypocolius)",
    "Promeropidae (Sugarbirds)",
    "Modulatricidae (Dapple-throat and Allies)",
    "Dicaeidae (Flowerpeckers)",
    "Nectariniidae (Sunbirds and Spiderhunters)",
    "Irenidae (Fairy-bluebirds)",
    "Chloropseidae (Leafbirds)",
    "Peucedramidae (Olive Warbler)",
    "Urocynchramidae (Przevalski's Pinktail)",
    "Ploceidae (Weavers and Allies)",
    "Estrildidae (Waxbills and Allies)",
    "Viduidae (Indigobirds)",
    "Prunellidae (Accentors)",
    "Passeridae (Old World Sparrows)",
    "Motacillidae (Wagtails and Pipits)",
    "Fringillidae (Finches, Euphonias, and Allies)",
    "Calcariidae (Longspurs and Snow Buntings)",
    "Rhodinocichlidae (Thrush-Tanager)",
    "Emberizidae (Old World Buntings)",
    "Passerellidae (New World Sparrows)",
    "Calyptophilidae (Chat-Tanagers)",
    "Phaenicophilidae (Hispaniolan Tanagers)",
    "Nesospingidae (Puerto Rican Tanager)",
    "Spindalidae (Spindalises)",
    "Zeledoniidae (Wrenthrush)",
    "Teretistridae (Cuban Warblers)",
    "Icteriidae (Yellow-breasted Chat)",
    "Icteridae (Troupials and Allies)",
    "Parulidae (New World Warblers)",
    "Mitrospingidae (Mitrospingid Tanagers)",
    "Cardinalidae (Cardinals and Allies)",
    "Thraupidae (Tanagers and Allies)",
    ""
];
let uniCategory = [
    "All",
    "species",
    "subspecies",
    "slash",
    "group (polytypic)",
    "group (monotypic)",
    "spuh",
    "hybrid",
    "domestic",
    "form",
    "intergrade",
    "spuh"
];